# -*- coding: utf-8 -*-
"""calculadora_inteligente.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jsCfbVn9tCPLxw4kn8R0YrruTzSWXLay

#Calculadora Inteligente
"""

nome = input("Qual o seu nome?")
print("Olá", nome, "seja bem vindo a nossa Calculadora Inteligente")

resposta = 0
print("Deseja calcular em nossa Calculadora Inteligente?")

resposta = input("Digite (S) para Sim ou (N) para Não. \n")
while resposta == "S" or resposta == "s":
  print("Ótimo, vamos lá!")

  num1 = 0
  num2 = 0

  num1 = float(input("Digite o primeiro número:"))
  print("O primeiro número escolhido é:", num1)
  num2 = float(input("Digite o segundo número:"))
  print("O segundo número escolhido é:", num2, "\n")

  operacao = 0

  print("As opções de operações são:")
  print("1 - Soma")
  print("2 - Subtração")
  print("3 - Multiplicação")
  print("4 - Divisão")
  operacao = input("Digite o número da operação que deseja realizar entre os dois números escolhidos:")
  print("A operação escolhida foi:", operacao)

  soma = 0
  subtracao = 0
  multiplicacao = 0
  divisao1 = 0
  divisao2 = 0

  if operacao == "1":
    soma = num1 + num2
    print("O resultado da operação é:", soma,"\n")
  elif operacao == "2":
    subtracao = num1 - num2
    print("O resultado da operação é:", subtracao,"\n")
  elif operacao == "3":
    multiplicacao = num1 * num2
    print("O resultado da operação é:", multiplicacao,"\n")
  elif operacao == "4":
    divisao1 = num1 / num2
    divisao2 = num1 % num2
    print("O resultado da operação é:", divisao1, "e o resto da divisão é",divisao2,"\n")

  resposta = input("Deseja calcular em nossa Calculadora Inteligente?")

else:
  print("Fim do programa")

